"""
License Manager — handles 5-day free trial + paid license verification.
100% OFFLINE — no server, no internet check needed.

SECURITY NOTE FOR THE OWNER:
─────────────────────────────────────────────────────────
This file only contains a PUBLIC KEY. It can VERIFY license keys
but CANNOT GENERATE new ones. Customers can read this entire file —
it doesn't help them create fake licenses. Safe to distribute.

HOW IT WORKS FOR YOU (THE OWNER):
─────────────────────────────────────────────────────────
1. Customer downloads the agent, runs it — 5-day trial starts automatically.
2. After 5 days, agent stops working until they enter a LICENSE KEY.
3. Customer pays ₹5000 (via your UPI/Razorpay link).
4. On YOUR machine (with private_key.pem present), run:
       python generate_license.py customer@email.com
5. Send them the generated key. They paste it into config.py.
6. Agent unlocks for 30 days. Repeat step 4-6 next month.
"""

import os, hmac, hashlib, base64, json
from datetime import datetime, timedelta
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
from cryptography.exceptions import InvalidSignature

# ══════════════════════════════════════════════════════
#  PUBLIC KEY — safe to share. Cannot generate licenses.
#  (Generated by generate_keys.py — paste your own here)
# ══════════════════════════════════════════════════════
PUBLIC_KEY_HEX = "e55310fa50948a3b8bc4a0d99efed071c92d5420f190504f9aaf07a8493fba22"

from paths import get_base_dir

BASE = get_base_dir()
TRIAL_FILE = os.path.join(BASE, ".trial_data")  # hidden file, tracks trial start
TRIAL_DAYS = 5

# Separate secret used ONLY for trial-file tamper protection (local, low stakes)
_TRIAL_SECRET = "trial-integrity-" + PUBLIC_KEY_HEX[:16]


def _sign_trial(data: str) -> str:
    return hmac.new(_TRIAL_SECRET.encode(), data.encode(), hashlib.sha256).hexdigest()[:16]


# ══════════════════════════════════════════════════════
#  TRIAL TRACKING
# ══════════════════════════════════════════════════════
def _read_trial_file():
    if not os.path.exists(TRIAL_FILE):
        return None
    try:
        with open(TRIAL_FILE) as f:
            data = json.load(f)
        if data.get("sig") != _sign_trial(data["start_date"]):
            return None
        return datetime.strptime(data["start_date"], "%Y-%m-%d").date()
    except Exception:
        return None


def _write_trial_file():
    start_date = str(datetime.now().date())
    data = {"start_date": start_date, "sig": _sign_trial(start_date)}
    with open(TRIAL_FILE, "w") as f:
        json.dump(data, f)
    return datetime.strptime(start_date, "%Y-%m-%d").date()


def get_trial_status():
    start = _read_trial_file()
    if start is None:
        start = _write_trial_file()
    today = datetime.now().date()
    days_used = (today - start).days
    days_left = TRIAL_DAYS - days_used
    return (days_left > 0, max(days_left, 0), start)


# ══════════════════════════════════════════════════════
#  LICENSE KEY VERIFICATION (Ed25519 — asymmetric)
# ══════════════════════════════════════════════════════
def verify_license_key(customer_email: str, license_key: str):
    """
    Returns (is_valid: bool, message: str, days_left: int)
    Verifies a signature created by generate_license.py's PRIVATE key,
    using only the PUBLIC key embedded above.
    """
    if not license_key or not license_key.strip():
        return False, "No license key provided.", 0

    try:
        raw = base64.urlsafe_b64decode(license_key.strip().encode())
        # Format: payload_bytes || 64-byte signature
        payload_bytes = raw[:-64]
        signature     = raw[-64:]
        payload = payload_bytes.decode()
        email_in_key, expiry_str = payload.split("|")
    except Exception:
        return False, "License key is invalid (corrupted or wrong format).", 0

    try:
        public_key = Ed25519PublicKey.from_public_bytes(bytes.fromhex(PUBLIC_KEY_HEX))
        public_key.verify(signature, payload_bytes)
    except InvalidSignature:
        return False, "License key is invalid (signature check failed).", 0
    except Exception:
        return False, "License key is invalid (verification error).", 0

    if email_in_key.lower().strip() != customer_email.lower().strip():
        return False, "License key does not match this email address.", 0

    expiry_date = datetime.strptime(expiry_str, "%Y%m%d").date()
    today = datetime.now().date()
    days_left = (expiry_date - today).days

    if days_left < 0:
        return False, f"License expired on {expiry_date}. Please renew.", 0

    return True, f"License valid until {expiry_date}.", days_left


# ══════════════════════════════════════════════════════
#  MAIN CHECK — call this at the start of the agent
# ══════════════════════════════════════════════════════
def check_access(customer_email: str, license_key: str):
    if license_key and license_key.strip():
        valid, msg, days_left = verify_license_key(customer_email, license_key)
        if valid:
            print(f"  ✅ Licensed user — {msg} ({days_left} days left)")
            return True, msg
        else:
            print(f"  ❌ License problem: {msg}")

    trial_active, days_left, start_date = get_trial_status()
    if trial_active:
        print(f"  🎁 FREE TRIAL — {days_left} day(s) left "
              f"(started {start_date}, expires {start_date + timedelta(days=TRIAL_DAYS)})")
        print(f"     After trial ends, you'll need a license key (₹5000/month).")
        return True, "Trial active"
    else:
        print(f"\n  ⛔ Your {TRIAL_DAYS}-day free trial has ended.")
        print(f"     Trial started: {start_date}")
        print(f"\n  💳 To continue using AI Client Agent:")
        print(f"     1. Pay ₹5000 for 1 month access (see PAYMENT.txt)")
        print(f"     2. Send payment screenshot + your email to get a license key")
        print(f"     3. Paste the license key into config.py")
        print(f"     4. Run the agent again\n")
        return False, "Trial expired"
